services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  app:
    build: .
    environment:
      DATABASE_URL: "postgresql://user:password@postgres:5432/mydatabase"
    ports:
      - "3004:3004"
    depends_on:
      - postgres
    
volumes:
  postgres-data:
